  version: 0.2
  phases:
     build:
      commands:
        - echo Entered in build phase
        - mvn clean package
    post_build:
      commands:
        - echo build completed succefully
  artifacts:
    files:
      - target/test.jar
    discard-paths: yes
